### ISSUE TITLE
Custom License Key

### ISSUE THREAD

**Issue by ademirp-serapion** [castlabs/prestoplay-react-components#3]
How can I add my license key to the player configuration? I couldn't find it in the exposed props.

**Comment by thasso** [comment]
Hi @ademirp-serapion,

You can request a license through our website at https://castlabs.com/free-trials/

**Comment by ademirp-serapion** [comment]
Sure, I have the license. It's not clear how to use it with components. I found the example in the official documentation without react-components, just not sure how to use it with react-components

**Comment by ademirp-serapion** [comment]
Thanks for the info, 

The `Player` constructor is definitely the better place for it, so I'll need to place the license only on one place during the player initialization.

However, thanks for the info ;)
